-- Insert luxury cars with compelling marketing descriptions
-- All cars are set as available and approved

INSERT INTO cars (
  id,
  make,
  model,
  year,
  color,
  license_plate,
  category,
  description,
  primary_image_url,
  photos,
  video_url,
  transmission,
  fuel_type,
  seats,
  features,
  location_lat,
  location_lon,
  status,
  maintenance_status,
  last_maintenance_date,
  next_service_date,
  daily_rate,
  overtime_rate,
  security_deposit,
  is_approved,
  is_outsourced,
  created_at
) VALUES 
-- Toyota Camry
(
  gen_random_uuid(),
  'Toyota',
  'Camry',
  2024,
  'Pearl White',
  'KCB 123A',
  'Sedan',
  'Experience the perfect blend of elegance and efficiency with our 2024 Toyota Camry. This premium sedan offers unparalleled comfort, advanced safety features, and exceptional fuel economy. Whether you''re navigating Nairobi''s business districts or embarking on a weekend getaway, the Camry delivers a sophisticated driving experience that exceeds expectations.',
  'https://picsum.photos/seed/camry-2024/800/600.jpg',
  ARRAY['https://picsum.photos/seed/camry-2024/800/600.jpg'],
  '',
  'Automatic',
  'Hybrid',
  5,
  ARRAY['Leather Seats', 'Sunroof', 'GPS Navigation', 'Bluetooth', 'Cruise Control', 'Lane Assist', 'Adaptive Cruise Control', 'Premium Audio'],
  -1.2921,
  36.8219,
  'available',
  'ok',
  '2024-01-15',
  '2024-07-15',
  4500,
  500,
  15000,
  true,
  false,
  NOW()
),

-- Mercedes-Benz C-Class
(
  gen_random_uuid(),
  'Mercedes-Benz',
  'C-Class',
  2024,
  'Metallic Silver',
  'KCD 456B',
  'Luxury',
  'Indulge in pure luxury with our 2024 Mercedes-Benz C-Class. This masterpiece of German engineering combines cutting-edge technology with timeless elegance. From the handcrafted interior to the whisper-quiet engine, every detail speaks of sophistication. Perfect for making a lasting impression at business meetings or special occasions.',
  'https://picsum.photos/seed/c-class-2024/800/600.jpg',
  ARRAY['https://picsum.photos/seed/c-class-2024/800/600.jpg'],
  '',
  'Automatic',
  'Petrol',
  5,
  ARRAY['MBUX Infotainment', 'Burmester Audio', 'Ambient Lighting', 'Panoramic Sunroof', 'Heated Seats', 'Wireless Charging', 'Apple CarPlay', 'Android Auto'],
  -1.2921,
  36.8219,
  'available',
  'ok',
  '2024-01-20',
  '2024-07-20',
  8500,
  1000,
  25000,
  true,
  false,
  NOW()
),

-- Toyota Land Cruiser
(
  gen_random_uuid(),
  'Toyota',
  'Land Cruiser',
  2024,
  'Midnight Black',
  'KCE 789C',
  'SUV',
  'Conquer any terrain with confidence in our 2024 Toyota Land Cruiser. Built for adventure yet refined for comfort, this legendary SUV combines rugged capability with premium amenities. Perfect for safaris, family road trips, or navigating Kenya''s diverse landscapes with unmatched reliability and prestige.',
  'https://picsum.photos/seed/landcruiser-2024/800/600.jpg',
  ARRAY['https://picsum.photos/seed/landcruiser-2024/800/600.jpg'],
  '',
  'Automatic',
  'Diesel',
  7,
  ARRAY['4WD System', 'Multi-Terrain Select', 'Crawl Control', 'Third Row Seating', 'Premium Audio', 'Leather Interior', 'Roof Rails', 'Tow Hitch'],
  -1.2921,
  36.8219,
  'available',
  'ok',
  '2024-01-10',
  '2024-07-10',
  7500,
  900,
  20000,
  true,
  false,
  NOW()
),

-- BMW X5
(
  gen_random_uuid(),
  'BMW',
  'X5',
  2024,
  'Alpine White',
  'KCF 101D',
  'SUV',
  'Elevate your journey with the 2024 BMW X5, where performance meets luxury in perfect harmony. This dynamic SUV delivers sportscar-like agility with SUV versatility, wrapped in unmistakable BMW elegance. Ideal for those who demand excellence in every aspect of their driving experience.',
  'https://picsum.photos/seed/x5-2024/800/600.jpg',
  ARRAY['https://picsum.photos/seed/x5-2024/800/600.jpg'],
  '',
  'Automatic',
  'Petrol',
  7,
  ARRAY['xDrive AWD', 'Live Cockpit Professional', 'Harman Kardon Audio', 'Panoramic Roof', 'Heated Steering Wheel', 'Gesture Control', 'Wireless Charging', 'Head-Up Display'],
  -1.2921,
  36.8219,
  'available',
  'ok',
  '2024-01-25',
  '2024-07-25',
  9000,
  1200,
  30000,
  true,
  false,
  NOW()
),

-- Audi A4
(
  gen_random_uuid(),
  'Audi',
  'A4',
  2024,
  'Naval Blue',
  'KCG 234E',
  'Luxury',
  'Discover automotive perfection with our 2024 Audi A4. This compact luxury sedan represents the pinnacle of German engineering, offering refined performance, cutting-edge technology, and understated elegance. Perfect for the discerning driver who appreciates subtlety and sophistication.',
  'https://picsum.photos/seed/a4-2024/800/600.jpg',
  ARRAY['https://picsum.photos/seed/a4-2024/800/600.jpg'],
  '',
  'Automatic',
  'Petrol',
  5,
  ARRAY['Virtual Cockpit', 'Bang & Olufsen Audio', 'Quattro AWD', 'Matrix LED Headlights', 'Leather Seats', 'Adaptive Cruise', 'Parking Assist', 'Wireless Charging'],
  -1.2921,
  36.8219,
  'available',
  'ok',
  '2024-01-18',
  '2024-07-18',
  7000,
  850,
  22000,
  true,
  false,
  NOW()
),

-- Nissan Patrol
(
  gen_random_uuid(),
  'Nissan',
  'Patrol',
  2024,
  'Bronze Metallic',
  'KCH 567F',
  'SUV',
  'Command attention with our 2024 Nissan Patrol, the ultimate expression of power and prestige. This full-size luxury SUV combines commanding presence with exceptional off-road capability and premium comfort. Perfect for those who refuse to compromise on adventure or luxury.',
  'https://picsum.photos/seed/patrol-2024/800/600.jpg',
  ARRAY['https://picsum.photos/seed/patrol-2024/800/600.jpg'],
  '',
  'Automatic',
  'Petrol',
  8,
  ARRAY['4WD System', 'Intelligent Around View', 'Leather Interior', 'Premium Audio', 'Climate Control', 'Roof Rails', 'Tow Package', 'Remote Start'],
  -1.2921,
  36.8219,
  'available',
  'ok',
  '2024-01-12',
  '2024-07-12',
  8000,
  1000,
  25000,
  true,
  false,
  NOW()
),

-- Honda CR-V
(
  gen_random_uuid(),
  'Honda',
  'CR-V',
  2024,
  'Crystal Black',
  'KCM 890G',
  'SUV',
  'Experience versatile excellence with our 2024 Honda CR-V. This compact SUV perfectly balances practicality, efficiency, and style. Ideal for urban adventures and weekend escapes alike, offering Honda''s legendary reliability with modern comfort and advanced safety features.',
  'https://picsum.photos/seed/crv-2024/800/600.jpg',
  ARRAY['https://picsum.photos/seed/crv-2024/800/600.jpg'],
  '',
  'Automatic',
  'Hybrid',
  5,
  ARRAY['Honda Sensing', 'Apple CarPlay', 'Android Auto', 'Leather Seats', 'Moonroof', 'Dual Zone Climate', 'Power Tailgate', 'Heated Seats'],
  -1.2921,
  36.8219,
  'available',
  'ok',
  '2024-01-22',
  '2024-07-22',
  5500,
  650,
  18000,
  true,
  false,
  NOW()
),

-- Lexus RX 350
(
  gen_random_uuid(),
  'Lexus',
  'RX 350',
  2024,
  'Obsidian Black',
  'KCN 345H',
  'Luxury',
  'Immerse yourself in luxury with our 2024 Lexus RX 350. This premium SUV redefines comfort and sophistication, offering whisper-quiet operation, exquisite craftsmanship, and cutting-edge technology. Every journey becomes an experience in pure indulgence.',
  'https://picsum.photos/seed/rx350-2024/800/600.jpg',
  ARRAY['https://picsum.photos/seed/rx350-2024/800/600.jpg'],
  '',
  'Automatic',
  'Petrol',
  7,
  ARRAY['Mark Levinson Audio', 'Panoramic Roof', 'Heated & Ventilated Seats', 'Head-Up Display', 'Wireless Charging', 'Apple CarPlay', 'Android Auto', 'Advanced Safety'],
  -1.2921,
  36.8219,
  'available',
  'ok',
  '2024-01-28',
  '2024-07-28',
  9500,
  1300,
  35000,
  true,
  false,
  NOW()
);
